# Generated by Django 4.2.16 on 2024-10-10 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='files/contents')),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_type', models.TextField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='files/channels')),
                ('language', models.CharField(choices=[('ES', 'SPANISH'), ('EN', 'ENGLISH'), ('CA', 'CATALAN'), ('PT', 'PORTUGUESE')], max_length=3)),
                ('contents', models.ManyToManyField(blank=True, to='platform_app.content')),
                ('subchannels', models.ManyToManyField(blank=True, to='platform_app.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_app.content')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_app.metadatatype')),
            ],
            options={
                'unique_together': {('metadata_type', 'content')},
            },
        ),
    ]
